config/routes.rb
Rails.application.routes.draw do
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get '/',                        to: 'home#index'
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    resources :products,            only: :show do
      get :search,                  on: :collection
    end
    resources :categories,          only: :show
    resources :orders,              only: %i[edit update] do
      post :populate,               on: :collection
      delete :remove_line_item,     on: :member
    end
    get   '/cart',                  to: 'orders#edit'
    patch '/cart',                  to: 'orders#update'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/potepan/product_decorator.rb
module Potepan::ProductDecorator
  #===== クラスメソッド =====
  def self.prepended(base)
    def base.new_arrival_from(from)
      where(available_on: from..Time.zone.today)
        .order(available_on: 'DESC')
        .includes(master: %i[default_price images])
    end
  end

  #===== インスタンスメソッド =====
  def extract_related_products
    Spree::Product.in_taxons(taxons)
                  .includes(master: %i[default_price images])
                  .where.not(id: id)
                  .distinct
  end
  Spree::Product.prepend self
end

app/models/potepan/taxon_decorator.rb
module Potepan::TaxonDecorator
  #===== インスタンスメソッド =====
  def products_sort(sort_type)
    Spree::Product
      .joins(:taxons).where(spree_taxons: { id: self_and_descendants.ids })
      .includes(:variants, master: %i[images default_price])
      .eager_load(variants: %i[prices])
      .distinct
      .order(order_sentence(sort_type))
  end

  def order_sentence(sort_type)
    case sort_type
    when 'NEW_PRODUCTS'
      'spree_products.available_on DESC'
    when 'OLD_PRODUCTS'
      'spree_products.available_on ASC'
    when 'LOW_PRICE'
      'default_prices_spree_variants.amount ASC'
    when 'HIGH_PRICE'
      'default_prices_spree_variants.amount DESC'
    end
  end

  Spree::Taxon.prepend self
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  DEFAULT_SORT = 'NEW_PRODUCTS'
  def show
    @taxon = Spree::Taxon.find(params[:id])
    @taxonomies = Spree::Taxonomy.includes(:root)
    @colors = Spree::OptionValue.joins(:option_type).where('spree_option_types.presentation like ?', '%color%')
    @sizes = Spree::OptionValue.joins(:option_type).where('spree_option_types.presentation like ?', '%size%')
    @colors_info = {}
    @colors.each do |color|
      value = Spree::Product.in_taxon(@taxon)
                            .joins(variants: :option_values)
                            .where(spree_option_values: { name: color.name })
                            .distinct
                            .count
      @colors_info[color.name.to_sym] = value
    end
    @sizes_info = {}
    @sizes.each do |size|
      value = Spree::Product.in_taxon(@taxon)
                            .joins(variants: :option_values)
                            .where(spree_option_values: { name: size.name })
                            .distinct
                            .count
      @sizes_info[size.name.to_sym] = value
    end
    @products = if params[:sort]
                  @taxon.products_sort(params[:sort])
                elsif params[:color]
                  Spree::Product.in_taxon(@taxon)
                                .includes(master: %i[default_price images])
                                .includes(variants: :option_values)
                                .where(spree_option_values: { name: params[:color] })
                elsif params[:size]
                  Spree::Product.in_taxon(@taxon)
                                .includes(master: %i[default_price images])
                                .includes(variants: :option_values)
                                .where(spree_option_values: { name: params[:size] })
                else
                  @taxon.products_sort(DEFAULT_SORT)
                end
  end
end

app/controllers/potepan/home_controller.rb
class Potepan::HomeController < ApplicationController
  POPULAR_TAXONS = ["shirts", "bags", "mugs"].freeze
  def index
    @new_arrival_products = Spree::Product.new_arrival_from(2.weeks.ago) ||
                            Spree::Product.includes(master: %i[default_price images])
                                          .order(available_on: 'DESC')
    @popular_taxons = Spree::Taxon.where(name: POPULAR_TAXONS)
  end
end

app/controllers/potepan/orders_controller.rb
class Potepan::OrdersController < ApplicationController
  include Spree::Core::ControllerHelpers::Order
  include Spree::Core::ControllerHelpers::Store
  include Spree::Core::ControllerHelpers::Auth

  def edit
    @order =
      current_order ||
      Spree::Order.incomplete.find_or_initialize_by(
        guest_token: cookies.signed[:guest_token]
      )
  end

  def update
    @order = Spree::Order.find(params[:id])
    @order.contents.update_cart(order_params)
    redirect_to potepan_cart_path
  end

  def remove_line_item
    line_item = Spree::LineItem.find(params[:id])
    line_item.order.contents.remove_line_item(line_item)
    redirect_to potepan_cart_path
  end

  def populate
    @order = current_order(create_order_if_necessary: true)
    authorize! :update, @order, cookies.signed[:guest_token]

    variant  = Spree::Variant.find(params[:variant_id])
    quantity = params[:quantity].present? ? params[:quantity].to_i : 1

    begin
      @line_item = @order.contents.add(variant, quantity)
    rescue ActiveRecord::RecordInvalid => e
      @order.errors.add(:base, e.record.errors.full_messages.join(', '))
    end

    if @order.errors.any?
      flash[:error] = @order.errors.full_messages.join(', ')
      redirect_back_or_default(potepan_path)
      return
    else
      redirect_to potepan_cart_path
    end
  end

  private

  def order_params
    params.require(:order).permit(line_items_attributes: %i[id quantity])
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  RELATED_PRODUCTS_DISPLAY_MAX = 4
  def show
    @product = Spree::Product.find(params[:id])
    @images  = @product.images
    @related_products = @product.extract_related_products
                                .limit(RELATED_PRODUCTS_DISPLAY_MAX)
    @taxon = @product.taxons.first
  end

  def search
    @products = if params[:search]
                  Spree::Product.includes(master: %i[default_price images])
                                .where(['name LIKE ? OR description LIKE ?', "%#{params[:search]}%", "%#{params[:search]}%"])
                else
                  Spree::Product.includes(master: %i[default_price images])
                end
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_page_title(title)
    base_title = 'BIGBAG Store'
    if title.blank?
      base_title
    else
      "#{title} - #{base_title}"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <%= render 'layouts/partials/head' %>
  </head>
  <body>
    <!-- HEADER -->
    <%= render 'layouts/partials/header' %>
    <%= yield %>
    <!-- FOOTER -->
    <%= render 'layouts/partials/footer' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/layouts/partials/_footer.html.erb
<!-- COPY RIGHT -->
<div id="footer" class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2016-<%= Time.zone.now.year %> Copyright Potepan Store .</p>
      </div>
      <div class="col-sm-5 col-xs-12">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/partials/_head.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag 'application', media: 'all' %>
<!-- SITE TITTLE -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title><%= full_page_title(yield(:title)) %></title>
<!-- PLUGINS CSS STYLE -->
<%= stylesheet_link_tag "application", :media => "all" %>
<!-- GOOGLE FONT -->
<%= stylesheet_link_tag "application", 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/partials/_header.html.erb
<div class="header clearfix">
  <!-- TOPBAR -->
  <div class="topBar">
    <div class="container">
      <div class="row">
        <div class="col-md-6 hidden-sm hidden-xs">
          <ul class="list-inline">
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          </ul>
        </div>
        <div class="col-md-6 col-xs-12">
          <ul class="list-inline pull-right">
            <li></li>
            <li class="dropdown searchBox">
              <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">
                <i class="fa fa-search"></i>
              </a>
              <ul class="dropdown-menu dropdown-menu-right">
                <%= form_tag(search_potepan_products_path, id: "form01", method: "get", enforce_utf8: false) do %>
                  <li>
                    <span class="input-group">
                      <%= text_field_tag :search, "", class: "form-control", placeholder: "Search…", aria_describedby: "basic-addon2" %>
                      <button>
                        <span class="input-group-addon" id="basic-addon2" onclick="this.form.submit()">検索</span>
                      </button>
                    </span>
                  </li>
                <% end %>
              </ul>
            </li>
            <li class="dropdown">
              <a href="<%= potepan_cart_path %>" class="dropdown-toggle" data-toggle="dropdown disabled" id="shopping-cart">
                <i class="fa fa-shopping-cart"></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <!-- NAVBAR -->
  <nav class="navbar navbar-main navbar-default" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <%= link_to potepan_path do %>
          <%= image_tag("img/logo.png", :alt => "title_logo", class: "navbar-brand") %>
        <% end %>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'HOME', potepan_path %></li>
          <li class="dropdown megaDropMenu active">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false">SHOP</a>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
  </nav>
</div>

app/views/potepan/categories/_side_bar.html.erb
<div class="col-md-3 col-sm-4 col-xs-12 sideBar">
  <div class="panel panel-default">
    <div class="panel-heading">商品カテゴリー</div>
    <div class="panel-body">
      <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
        <ul class="nav navbar-nav side-nav">
          <% taxonomies.each_with_index do |taxonomy, i| %>
            <li>
              <a href="javascript:;" data-toggle="collapse" data-target="#taxonomy-<%= i %>">
                <%= taxonomy.name %>
                <i class="fa fa-plus"></i>
              </a>
              <ul id="taxonomy-<%= i %>" class="collapse collapseItem">
                <% taxonomy.root.leaves.each do |leaf| %>
                  <li>
                    <%= link_to potepan_category_path(leaf.id) do %>
                      <i class="fa fa-caret-right" aria-hidden="true"></i>
                      <%= leaf.name %> <span><%= "(#{leaf.products.count})" %></span>
                    <% end %>
                  </li>
                <% end %>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="panel panel-default filterNormal">
    <div class="panel-heading">色から探す</div>
    <div class="panel-body">
      <ul class="list-unstyled">
        <% colors.each do |color| %>
          <li>
            <%= link_to potepan_category_path(color: color.name) do %>
              <%= color.presentation %><span><%= "(#{@colors_info[ color.name.to_sym ]})" %></span>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="panel panel-default filterNormal">
    <div class="panel-heading">サイズから探す</div>
    <div class="panel-body">
      <ul class="list-unstyled clearfix">
        <% sizes.each do |size| %>
          <li>
            <%= link_to potepan_category_path(size: size.name) do %>
              <%= size.presentation %><span><%= "(#{@sizes_info[ size.name.to_sym ]})" %></span>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/potepan/categories/_small_header.html.erb
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= taxon.name %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to 'Home', potepan_path %>
          </li>
          <li>
            <a href="#">shop</a>
          </li>
          <li class="active"><%= taxon.name %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/potepan/categories/_sort_filter.html.erb
<div class="row filterArea">
  <div class="col-xs-6">
    <select name="guiest_id1" id="guiest_id1" class="select-drop">
      <option value="NEW_PRODUCTS">新着順</option>
      <option value="LOW_PRICE">安い順</option>
      <option value="HIGH_PRICE">高い順</option>
      <option value="OLD_PRODUCTS">古い順</option>
    </select>
  </div>
  <div class="col-xs-6">
    <div class="btn-group pull-right" role="group">
      <button type="button" class="btn btn-default active" onclick="window.location.href='product_grid_left_sidebar.html'"><i class="fa fa-th" aria-hidden="true"></i><span>Grid</span></button>
      <button type="button" class="btn btn-default" onclick="window.location.href='product_list_left_sidebar.html'"><i class="fa fa-th-list" aria-hidden="true"></i><span>List</span></button>
    </div>
  </div>
</div>

app/views/potepan/categories/show.html.erb
<% provide :title, @taxon.name %>
<div class="main-wrapper">
  <%= render 'small_header', taxon: @taxon %>
  <!-- MAIN CONTENT SECTION -->
  <section class="mainContent clearfix productsContent">
    <div class="container">
      <div class="row">
        <%= render 'side_bar', taxonomies: @taxonomies, colors: @colors, colors_info: @colors_info, sizes: @sizes, sizes_info: @sizes_info %>
        <div class="col-md-9 col-sm-8 col-xs-12">
          <%= render 'sort_filter' %>
          <div class="row">
            <% @products.each do |product| %>
              <div class="col-sm-4 col-xs-12">
                <%= link_to potepan_product_path(product.id) do %>
                  <div class="productBox">
                    <div class="productImage clearfix">
                      <%= image_tag(product.display_image.attachment(:product), :alt => "products-img") %>
                    </div>
                    <div class="productCaption clearfix">
                      <h5><%= product.name %></h5>
                      <h3><%= product.display_price %></h3>
                    </div>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </section>
  <%= render 'potepan/shared/partner_logo_slider' %>
</div>
<%= render 'potepan/shared/login_modal' %>
<%= render 'potepan/shared/sign_up_modal' %>

app/views/potepan/home/_banner.html.erb
<div class="bannercontainer">
  <div class="fullscreenbanner-container">
    <div class="fullscreenbanner">
      <ul>
        <li>
          <%= image_tag("home/banner-slider/slider-bg.jpg", :alt => "slidebg1", data: { bgposition: "center center", bgfit: "cover" , bgrepeat: "no-repeat" }) %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/potepan/home/_new_arrival_products.html.erb
<div class="row featuredProducts">
  <div class="col-xs-12">
    <div class="page-header">
      <h4>新着商品</h4>
    </div>
  </div>
  <div class="col-xs-12">
    <div class="owl-carousel featuredProductsSlider">
      <% new_arrival_products.each do |new_arrival_product| %>
        <div class="slide">
          <%= link_to potepan_product_path(new_arrival_product.id) do %>
            <div class="productImage clearfix">
              <%= image_tag(new_arrival_product.display_image.attachment(:product), :alt => "featured-product-img") %>
            </div>
            <div class="productCaption clearfix">
              <h5><%= new_arrival_product.name %></h5>
              <h3><%= new_arrival_product.display_price %></h3>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/potepan/home/_popular_categories.html.erb
<div class="row featuredCollection">
  <div class="col-xs-12">
    <div class="page-header">
      <h4>人気カテゴリー</h4>
    </div>
  </div>
  <% popular_categories.each do |popular_category| %>
    <div class="col-sm-4 col-xs-12">
      <%= link_to potepan_category_path(popular_category.id) do %>
        <div class="thumbnail">
          <div class="imageWrapper">
            <%= image_tag("home/featured-collection/featured-collection-#{popular_category.name}.jpg", :alt => "feature-collection-image") %>
            <div class="masking">
              <div class="btn viewBtn">View <%= popular_category.name %></div>
            </div>
          </div>
          <div class="caption">
            <h4><%= popular_category.name %></h4>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/potepan/home/_product_quick_view_modal.html.erb
<div class="modal fade quick-view" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <div class="media">
          <div class="media-left">
            <%= image_tag("products/quick-view/quick-view-01.jpg", :class => "media-object", :alt => "Image") %>
          </div>
          <div class="media-body">
            <h2>Old Skool Navy</h2>
            <h3>149円</h3>
            <p>Classic sneaker from Vans. Cotton canvas and suede upper. Textile lining with heel stabilizer and ankle support. Contrasting laces. Sits on a classic waffle rubber sole.</p>
            <span class="quick-drop">
              <select name="guiest_id3" id="guiest_id3" class="select-drop">
                <option value="0">S</option>
                <option value="1">M</option>
                <option value="2">L</option>
                <option value="3">XL</option>
              </select>
            </span>
            <span class="quick-drop resizeWidth">
              <select name="guiest_id4" id="guiest_id4" class="select-drop">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
              </select>
            </span>
            <div class="btn-area">
              <a href="cart_page.html" class="btn btn-primary btn-block">カートへ入れる <i class="fa fa-angle-right" aria-hidden="true"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/potepan/home/index.html.erb
<div class="main-wrapper">
  <%= render 'banner' %>
  <!-- MAIN CONTENT SECTION -->
  <section class="mainContent clearfix">
    <div class="container">
      <%= render 'popular_categories', popular_categories: @popular_taxons %>
      <%= render 'new_arrival_products', new_arrival_products: @new_arrival_products %>
    </div>
  </section>
  <%= render 'potepan/shared/partner_logo_slider' %>
</div>
<%= render 'potepan/shared/login_modal' %>
<%= render 'potepan/shared/sign_up_modal' %>
<%= render 'product_quick_view_modal' %>

app/views/potepan/orders/_line_item.html.erb
<%= order_form.fields_for :line_items, line_item do |item_form| %>
  <tr>
    <td class="col-xs-2">
      <%= link_to(remove_line_item_potepan_order_path(line_item.id), method: :delete) do %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      <% end %>
      <span class="cartImage">
        <%= image_tag(line_item.variant.display_image.attachment(:product), alt: "image") %>
      </span>
    </td>
    <td class="col-xs-4"><%= line_item.name %></td>
    <td class="col-xs-2"><%= line_item.display_price %></td>
    <td class="col-xs-2">
      <%= item_form.number_field :quantity, min: 1, class: "line_item_quantity", size: 99 %>
    </td>
    <td class="col-xs-2"><%= line_item.display_amount %></td>
  </tr>
<% end %>

app/views/potepan/orders/_small_header.html.erb
<section class="lightSection clearfix pageHeaderImage">
  <div class="container">
    <div class="tableBlock">
      <div class="row tableInner">
        <div class="col-xs-12">
          <div class="page-title">
            <h2>cart</h2>
            <ol class="breadcrumb">
              <li>
                <%= link_to('Home', potepan_path) %>
              </li>
              <li class="active">cart</li>
            </ol>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/products/_cart_form.html.erb
<%= form_for :order, url: populate_potepan_orders_path do |f| %>
  <% if product.variants.any? %>
    <span class="quick-drop">
      <%= select_tag :variant_id, options_from_collection_for_select(product.variants, :id, :options_text), class: "select-drop" %>
    </span>
  <% else %>
    <%= hidden_field_tag "variant_id", product.master.id %>
  <% end %>
  <span class="quick-drop resizeWidth">
    <%= select_tag :quantity, options_for_select([*1..5]), class: "select-drop" %>
  </span>
  <div class="btn-area">
    <%= button_tag(type: 'submit', class: "btn btn-primary btn-block") do %>
      カートへ入れる
      <i class="fa fa-angle-right" aria-hidden="true"></i>
    <% end %>
  </div>
<% end %>

app/views/potepan/products/_related_products.html.erb
<div class="row productsContent">
  <div class="col-xs-12">
    <div class="page-header">
      <h4>関連商品</h4>
    </div>
  </div>
  <% related_products.each do |related_product| %>
    <div class="col-md-3 col-sm-6 col-xs-12">
      <%= link_to potepan_product_path(related_product.id) do %>
        <div class="productBox">
          <div class="productImage clearfix">
            <%= image_tag(related_product.display_image.attachment(:product), :alt => "products-img") %>
          </div>
          <div class="productCaption clearfix">
            <h5><%= related_product.name %></h5>
            <h3><%= related_product.display_price %></h3>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/potepan/products/search.html.erb
<% provide(:title, "検索結果") %>
<div class="main-wrapper">
  <%= render 'small_header' %>
  <!-- MAIN CONTENT SECTION -->
  <section class="mainContent clearfix productsContent">
    <div class="container">
      <div class="row">
        <div class="row">
          <% @products.each do |product| %>
            <div class="col-sm-3 col-xs-12">
              <%= link_to potepan_product_path(product.id) do %>
                <div class="productBox">
                  <div class="productImage clearfix">
                    <%= image_tag(product.display_image.attachment(:product), :alt => "products-img") %>
                  </div>
                  <div class="productCaption clearfix">
                    <h5><%= product.name %></h5>
                    <h3><%= product.display_price %></h3>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </section>
  <%= render 'potepan/shared/partner_logo_slider' %>
</div>
<%= render 'potepan/shared/login_modal' %>
<%= render 'potepan/shared/sign_up_modal' %>

app/views/potepan/products/show.html.erb
<% provide :title, @product.name %>
<div class="main-wrapper">
  <!-- LIGHT SECTION -->
  <section class="lightSection clearfix pageHeader">
    <div class="container">
      <div class="row">
        <div class="col-xs-6">
          <div class="page-title">
            <h2><%= @product.name %></h2>
          </div>
        </div>
        <div class="col-xs-6">
          <ol class="breadcrumb pull-right">
            <li><%= link_to 'Home', potepan_path %></li>
            <li class="active"><%= @product.name %></li>
          </ol>
        </div>
      </div>
    </div>
  </section>
  <!-- MAIN CONTENT SECTION -->
  <section class="mainContent clearfix">
    <div class="container">
      <div class="row singleProduct">
        <div class="col-xs-12">
          <div class="media">
            <div class="media-left productSlider">
              <div id="carousel" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                  <%= render 'product_slide_image', images: @images %>
                </div>
              </div>
              <div class="clearfix">
                <div id="thumbcarousel" class="carousel slide" data-interval="false">
                  <div class="carousel-inner">
                    <%= render 'product_thumb_image', images: @images %>
                  </div>
                  <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                  </a>
                  <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                  </a>
                </div>
              </div>
            </div>
            <div class="media-body">
              <ul class="list-inline">
                <li>
                  <%= link_to potepan_category_path(@taxon.id) do %>
                    <i class="fa fa-reply" aria-hidden="true"></i>
                    一覧ページへ戻る
                  <% end %>
                </li>
              </ul>
              <h2><%= @product.name %></h2>
              <h3><%= @product.display_price %></h3>
              <p><%= @product.description %></p>
              <%= render 'cart_form', product: @product %>
            </div>
          </div>
        </div>
      </div>
      <%= render 'related_products', related_products: @related_products %>
    </div>
  </section>
</div>
<%= render 'potepan/shared/login_modal' %>
<%= render 'potepan/shared/sign_up_modal' %>